version: "3.7"

services:
  frontend:
    container_name: react-dockerize
    restart: 'always'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true